### ISSUE TITLE
PyChess closing when playing online is not intuitive

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#274]
Original [issue 274](https://code.google.com/p/pychess/issues/detail?id=274) reported by [lobais](https://code.google.com/u/lobais/) 2007-12-21

**What steps will reproduce the problem?**
1. Start a FICS game
2. Finish it
3. Close the game window

**What is the expected output? What do you see instead?**

PyChess now asks if it you'd want to save the game, and after that the
entire application shuts down.

The user may think he/she can just return the the lounge window, but it
shuts down as well.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=274#c1) posted by [lobais](https://code.google.com/u/lobais/) 2010-06-24

This has to be Post Stauton. It is too much of a new paradigme.
- removed label: Stauton
- added label: Post-0.10

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=274#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-06-27
- removed label: Post-0.10
- added label: Post-0.12

**Comment by massimiliano-leoni** [comment]
I also consider this counter intuitive, when closing a finished online match I would expect to go back and play another one, not exiting the application.

**Comment by gbtami** [comment]
This was fixed years ago. Can you reproduce it with latest 0.12rc3 or with git version now?

**Comment by massimiliano-leoni** [comment]
Oops, sorry for necroposting.
Anyways I still have this on debian testing, version 0.12~beta3-1.
Maybe the debian package is out of date?

**Comment by massimiliano-leoni** [comment]
Just tried with the deb package form the website which is 0.12rc3. It still happens, with this error message in the terminal http://pastebin.com/yZCgPaED

**Comment by gbtami** [comment]
Works ok on Debian8 in Virtualbox for me. What distro are you using?

**Comment by massimiliano-leoni** [comment]
I'm on debian testing, which supposedly has newer software than debian 8 [current stable].

**Comment by gbtami** [comment]
Is it reproducible?

**Comment by massimiliano-leoni** [comment]
Currently, of course, it is.

**Comment by gbtami** [comment]
Ok, I'v installed debian testing from today netinst snapshot CD, but it can't boot :(
Anyhow we have ported pychess to gtk3/pygi so the next release will be rather different inside. Can you try git version too, please?

**Comment by massimiliano-leoni** [comment]
I cloned the current version but cannot run it: it complains

```
ERROR: Could not load the gtksourceview2 python module.
You need to install the gtksourceview2 python package which is 
called pygtksourceview in most distributions
```

I have python-gtksourceview from the repos installed, have no python-***-dev package in the repos and can run fine the repo version of pychess.
In the dev version, pychess tries `from gi.repository import GtkSource` and throws, whereas on the debian version I have `import gtksourceview2` which works

**Comment by gbtami** [comment]
I'v forgot to mention that git version has different dependencies listed in INSTALL file. Sorry!

**Comment by massimiliano-leoni** [comment]
Ok, installed missing dependencies and tried again. This time, not only I can still reproduce it, but during play I can't see the pieces moving, and I get this in the terminal: http://pastebin.com/DfdPfXT5

**Comment by gbtami** [comment]
Unfortunately I can't reproduce these because my fresh debian testing install in virtualbox starts, but with a black screen only :(

From pastebin traceback I see something wrong with playing game end sound. Are you sure you installed all listed dependencies?
What exactly "I can't see the pieces moving" mean?

**Comment by massimiliano-leoni** [comment]
Yes, all dependencies are installed.
See the screenshot for the "not moving pieces":
![screenshot1](https://cloud.githubusercontent.com/assets/12351309/8273484/7f0a721c-1870-11e5-9976-4966b97002e0.jpeg)
I moved the white pawn, drop it and it didn't go into place; afterwards, black moved [cfr move list] but the board didn't update.

**Comment by gbtami** [comment]
Ok, finally I was able to fix X in virtualbox and now I have a fresh (default) debian testing. Unfortunately I can't reproduce nor the original shutdown problem, nor the gstreamer problem from your pastebin :( Moving pieces is ok too.
What are your differences from the default install? DE, others?

**Comment by massimiliano-leoni** [comment]
Only thing I can think of, I'm with KDE, whereas PyChess is a GTK+ application...
But if it's just me, just let it go: I can remember to use Ctrl+W at the end of a game and it'll get fixed when I re-install.

**Comment by gbtami** [comment]
I can think you just hit one of our threading issues (freezes?) we started to get rid of in idle_add branch.

**Comment by gbtami** [comment]
@massimiliano-leoni I'v merged the idle_add branch to master, so if this was a threading issue it should be solved now. Can you give it another try, please?

**Comment by massimiliano-leoni** [comment]
Hi, sorry for my late reply.
I tried just now: I still have both issues, but clicking on the moves in the list triggers a screen refresh that updates the position. This has to be done at every move, though.

**Comment by gbtami** [comment]
@massimiliano-leoni, is this still reproducible with latest sources?

**Comment by massimiliano-leoni** [comment]
Yes, all of it.

**Comment by gbtami** [comment]
Are you sure you are running pychess git not an installed version?

**Comment by massimiliano-leoni** [comment]
v0.12rc3. I pulled from the repo just before posting my last comment.

**Comment by gbtami** [comment]
Just in case I'v updated the version string to "rc4". Can you verify it in "About" menu, please?

**Comment by massimiliano-leoni** [comment]
I verified, I am using the git version. Both bugs still present.

**Comment by gbtami** [comment]
Thx!

**Comment by gbtami** [comment]
OK, I finally managed to install debian testing and KDE in Virtualbox. Tried gnome, gnome-classic, xfce, kde5 with both python and python3, but unfortunately can't reproduce these. What other can be different on your part? (Btw. KDE5 seems rather good!)
ps.: Do you use up to date Debian testing? Do you use any special version of packages related to PyChess?

**Comment by massimiliano-leoni** [comment]
I am sorry you got into so much trouble for nothing :(
I don't know what other causes could be: debian testing is a rolling, bleeding edge system, so it's likely that at some point in the past something broke, and this is one of the consequences. If you can confirm that the bug is not reproducible in a fresh install, then we can close this.

[KDE5 -- technically, Plasma 5 -- IS rather good! Mine has a few glitches and bugs and some things are broken, but I upgraded from a KDE4 without reinstalling so this might be a cause for that. If you like it, how about porting Pychess to Qt5? It has python bindings :D]

**Comment by gbtami** [comment]
OK, I close this issue now. If it reappears for others we can reopen. Anyhow, thx for testing!

I was thinking about to port to PyQt before, but as @mattgatto said it would be a huge work for very little gain. Not to mention we just ported from gtk2 to gtk3 :)

**Comment by massimiliano-leoni** [comment]
My pleasure! Thanks to you for this wonderful application.

**Comment by bboutkov** [comment]
This is actually still an issue for me as well, sorry I am late to the discussion. Running  the latest code on Ubuntu 15.04, GNOME Shell 3.14.4

for me to reproduce: Start new game, click on "x" to close the window -> Pychess shuts down instead of closing the window and returning to main seek screen.

**Comment by massimiliano-leoni** [comment]
That's a plot twist!!

@gbtami see? I am not crazy U.U :P

**Comment by gbtami** [comment]
@massimiliano-leoni I never thought you are :)
@borisboutkov strange. I'v dd ubuntu-gnome-15.04-desktop-amd64.iso to my pendrive, booted from it, installed http://www.pychess.org/download/pychess_0.12rc4-1_all.deb with Ubunto Software Center, but wasn't able to reproduce this :( 

Can you (both) reproduce this with Python2 and Python3 too?

**Comment by bboutkov** [comment]
Just installed the .deb from the software center and the error still remains! I also saw a traceback this time when starting from console : 
(pychess:15343): Gtk-WARNING **: Don't know color `Gdk.RGBA(red=1.000000, green=1.000000, blue=1.000000, alpha=1.000000)'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pychess/ic/ICLounge.py", line 1282, in onGameAdd
    GLib.idle_add(do_onGameAdd, games, game, priority=GLib.PRIORITY_LOW)
AttributeError: 'NoneType' object has no attribute 'idle_add'

**Comment by gbtami** [comment]
Can you (both) reproduce this shutdown bug with Python2 and Python3 too?

**Comment by bboutkov** [comment]
Sorry, but how do I choose which python to run with? For both the installed .deb and for the git code I run off of the executable and I dont see any args to pass a python version looking inside the file.

**Comment by gbtami** [comment]
python ./pychess
will run PyChess with your default python, but you can run with 2 or 3 directly:
python2 ./pychess
or
python3 ./pychess

(The python3-pychess package runs PyChess with python3.)

**Comment by bboutkov** [comment]
Just checked and both py2 and py3 have the same behaviour where the program shuts down after closing a game.

**Comment by gbtami** [comment]
Thx! I'v added a debug print line to let me know wether I'm on a good direction. Can you pull and try again, please? You should see some spawn_async PID=x lines where x should be >0. If this will print 0 PID, we find the source of this bug. If not, I have to think in another direction.

**Comment by bboutkov** [comment]
I think we are out of luck :(

[bbdesk:pychess][master]$ python2 ./pychess

(pychess:6775): Gtk-WARNING **: Don't know color `Gdk.RGBA(red=1.000000, 
green=1.000000, blue=1.000000, alpha=1.000000)'
spawn_async PID= 6793
spawn_async PID= 6797
spawn_async PID= 6798

[bbdesk:pychess][master]$ python3 ./pychess

(pychess:6813): Gtk-WARNING **: Don't know color `Gdk.RGBA(red=1.000000, 
green=1.000000, blue=1.000000, alpha=1.000000)'
spawn_async PID= 6832
spawn_async PID= 6835
spawn_async PID= 6836

**Comment by gbtami** [comment]
Thx! @borisboutkov do you have time to chat about this bug on IRC, please?
http://webchat.freenode.net/?channels=pychess&uio=d4

**Comment by massimiliano-leoni** [comment]
I also still have it with python2. With Python3 I don't even see the chessboard when the game starts, and I have an error with this backtrace [many copies]

```
Traceback (most recent call last):
  File "/tmp/pychess/lib/pychess/widgets/BoardControl.py", line 276, in motion_notify
    return self.currentState.motion(event.x, event.y)
  File "/tmp/pychess/lib/pychess/widgets/BoardControl.py", line 399, in motion
    cord = self.point2Cord(x, y)
  File "/tmp/pychess/lib/pychess/widgets/BoardControl.py", line 370, in point2Cord
    point = self.transPoint(x, y)
  File "/tmp/pychess/lib/pychess/widgets/BoardControl.py", line 362, in transPoint
    x, y = self.view.invmatrix.transform_point(x,y)
AttributeError: 'NoneType' object has no attribute 'transform_point'
```

**Comment by gbtami** [comment]
Committed a possible fix for shut down issue. Can you try it with current git, please?

**Comment by bboutkov** [comment]
still not fixed :[

**Comment by massimiliano-leoni** [comment]
Same for me!

**Comment by gbtami** [comment]
Can you git pull again and send me (my git name with usual gmail address) the .log of a session ended with this shut down bug, please? Or just put it somewhere public.
(.log files are in ~/.local/share/pychess)

**Comment by massimiliano-leoni** [comment]
Last commit fixed the bug for me!
Now I only have the graphic glitches.

**Comment by gbtami** [comment]
@massimiliano-leoni thx for confirming it!
I'v split the graphic related issues into #998 and #999  
If they are reproducible can you send me .log files created when these happens, please?
(Or just put them into somewhere public.)
